//'use strict';

//127.0.0.1.:8080 local host ,port 8080
//store the selections into variables...

//nodelist is like an array
//loop through the btns (nodelist)

const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');
const btnsOpenModal = document.querySelectorAll('.show-modal'); //displays all showmodal classes(3 datas) data as nodelist
console.log(btnsOpenModal); //all 3 btns stored in btnsOpenModal variable


//open modal fn
const openModal = function () {
  console.log('button clicked'); //click show modal btns to see no. of times btn clicked

 //working with classes
  modal.classList.remove('hidden');
  //read classlist property remove() and can add classes without dot behind class name

  overlay.classList.remove('hidden');
  //to show overlay remove hidden class ie., when we click remove hidden and make it show data (by clicking on buttons)

  //modal.style.display = 'block';
  //when hidden class has display:none in css and to make it visible give display:block
};

//loops over nodelist for all show modal buttons
for (let i = 0; i < btnsOpenModal.length; i++) {
  //console.log(btnsOpenModal[i].textContent);
  //add event listener/event handler to the element
  btnsOpenModal[i].addEventListener('click', openModal);
}

//close modal fn ,when we click cancel or click in overlay bg
const closeModal = function () {
  modal.classList.add('hidden');
  overlay.classList.add('hidden');
};

btnCloseModal.addEventListener('click', closeModal);
overlay.addEventListener('click', closeModal);

//keyboard events(global events)listen on whole doc ,not on particular element
//three keyboard events:keydown,keypress,keyup

//keyup-happens when we lift finger off the  keyboard
//keypress-fired continuously as we keep our finger on key
//keydown -fired as soon as press down the key

document.addEventListener('keydown', function (e) {
  console.log(e); //event obj
  console.log(e.key);
  if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
    //console.log('esc was pressed');
    closeModal();
  } //close the modal if it is visible
});
//keyboardEvent obj generated by js
